#define UART_GPS                1
#define gps_open(OFLAG)		uart_open(1,OFLAG)
#define gps_close()		uart_close(1 )
#define gps_read(BUF,N)		uart_read(1,BUF,N)
#define gps_write(BUF,N)		uart_write(1,BUF,N)
#define gps_sync()		uart_sync(1 )
#define gps_init(P_CFG)		uart_init(1,P_CFG)
#define gps_getc()		uart_getc(1 )
#define gps_putc(C)		uart_putc(1,C)
#define gps_peek()		uart_peek(1 )
#define gps_find(C)		uart_find(1,C)
#define gps_print(P_STR)		uart_print(1,P_STR)
#define gps_available()		uart_available(1 )
#define gps_clear()		uart_clear(1 )

#define UART_RS232              0
#define rs232_open(OFLAG)		uart_open(0,OFLAG)
#define rs232_close()		uart_close(0 )
#define rs232_read(BUF,N)		uart_read(0,BUF,N)
#define rs232_write(BUF,N)		uart_write(0,BUF,N)
#define rs232_sync()		uart_sync(0 )
#define rs232_init(P_CFG)		uart_init(0,P_CFG)
#define rs232_getc()		uart_getc(0 )
#define rs232_putc(C)		uart_putc(0,C)
#define rs232_peek()		uart_peek(0 )
#define rs232_find(C)		uart_find(0,C)
#define rs232_print(P_STR)		uart_print(0,P_STR)
#define rs232_available()		uart_available(0 )
#define rs232_clear()		uart_clear(0 )

