// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\ccsds_encoder\Randomized_Data.v
// Created: 2016-05-22 11:42:29
// 
// Generated by MATLAB 8.3 and HDL Coder 3.4
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Randomized_Data
// Source Path: ccsds_encoder/Randomized Data
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Randomizer
          (
           clk,
           reset,
           enb,
           In1,
           Out1,
           enout
          );


  input   clk;
  input   reset;
  input   enb;
  input   In1;
  output  Out1;
  output  enout;
  reg [7:0] pn_reg;  // ufix8
  wire enout;
  wire pn_out;
  wire pn_xorout;
  wire [7:0] pn_newvalue [0:1];  // ufix8 [2]
  wire [6:0] pn_value_shifted;  // ufix7_E1


  assign pn_newvalue[0] = pn_reg;

  assign pn_xorout = pn_newvalue[0][0] ^ pn_newvalue[0][3] ^ pn_newvalue[0][5] ^ pn_newvalue[0][7];

  assign pn_value_shifted = pn_newvalue[0][7:1];

  assign pn_newvalue[1] = {pn_xorout, pn_value_shifted};

  assign pn_out = pn_newvalue[0][0];

  always @ (posedge (clk ) or negedge reset)
    begin
      if (!reset || !enb) begin
        pn_reg <= 8'b11111111;
      end else begin
          pn_reg <= pn_newvalue[1];
      end
    end 

  assign Out1 = In1 ^ pn_out;
 assign enout=enb ? 1 : 0;

endmodule  // Randomized_Data

